by_type_lddt:
  _target_: modelhub.metrics.lddt.ByTypeLDDT
all_atom_lddt:
  _target_: modelhub.metrics.lddt.AllAtomLDDT
distogram:
  _target_: modelhub.metrics.distogram.DistogramLoss
distogram_comparisons:
  _target_: modelhub.metrics.distogram.DistogramComparisons
distogram_entropy:
  _target_: modelhub.metrics.distogram.DistogramEntropy
chiral_loss:
  _target_: modelhub.metrics.chiral.ChiralLoss
unresolved_rasa:
  _target_: modelhub.metrics.rasa.UnresolvedRegionRASA
