data:
  pdb_path: /media/scratch/datasets/ingraham_cath_dataset
  designability_csv: /media/scratch/datasets/ingraham_cath_dataset/all_esmfold_native_with_cath_gapped_with_tm_with_seq.csv
  fixed_size: 512
  bb_only: false  # use backbone coordinates only
  n_random_subset: 1000
  se3_augment: true  # randomly rotate and translate data
  translation_scale: 0.0  # scale of the translation augmentation
  overwrite_cache: false  # overwrite the cached dataset


num_workers: 10
batch_size: 16
out_dir: out_dir/eval/analysis/interpolants  # null to save in the dataset directory
analysis_name: "edm"
seed: 0
device: "cuda"

# Model options
denoiser_ckpt: /home/rshuai/research/huang_lab/allatom_design/out_dir/train_latent_denoiser/allatom_design/faithful-darkness-1955/checkpoints/ld-epoch01.ckpt

defaults:
  - _self_
  - interpolant: ../../atom_denoiser/interpolant/edm_interpolant

# analyses to run
viz_interpolant_noise:
  run: true
  interpolant: ${interpolant}
  # sigma_data: 2.3  # noise level for AR backbone shifted from previous residue CA
  sigma_data: 10.0
  s_min_override: 0.001
  s_max_override: null


viz_forward_traj_bb_scn:
  run: false
  denoiser_ckpt: ${denoiser_ckpt}
  align_models_to_idx: 0
  n_samples: 3
  n_traj_steps: 100
  traj_conect: false


hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
