# Wandb configuration
project: "allatom_design"  # Wandb project name
wandb_id: "richardshuai"  # Wandb username
exp_name: null # Wandb exp name
group: "eval_ld_debug" # Wandb group name

# Run settings
no_wandb: false  # Disable wandb logging
seed: 0
start_epoch: 0  # start evaluation after this epoch, 0 or null to start from the beginning
eval_every_n_ckpts: 1  # evaluate every n checkpoints, for speed
batch_size: 64
num_workers: 10

# Denoiser options
denoiser_train_dir: /media/scratch/huang_lab/allatom_design/allatom_design/if7_a8
out_dir: ${denoiser_train_dir}/eval_scn_pack_training

# Data options for overriding denoiser config (null values default to denoiser config)
data:
    pdb_path: /media/scratch/datasets/ingraham_cath_dataset
    designability_csv: /media/scratch/datasets/ingraham_cath_dataset/all_esmfold_native_with_cath_gapped_with_tm_with_seq.csv
    n_random_subset: null

subset_length_range: [64, 256]  # only evaluate on sequences within this length range

# Sidechain packing options
num_steps: 1  # number of denoiser steps
t_bb_start: 1.0  # time to start t_bb for sidechain packing, goes to 1.0 at end of denoising
scn_diffusion:
  num_steps_list: [1, 20, 100]  # number of diffusion steps for sidechain packing

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
