# Wandb configuration
project: "allatom_design"  # Wandb project name
wandb_id: "richardshuai"  # Wandb username
exp_name: null # Wandb exp name
group: "debug" # Wandb group name

# Run settings
no_wandb: true  # Disable wandb logging
seed: 0
start_epoch: 0  # start evaluation after this epoch, 0 or null to start from the beginning
eval_every_n_ckpts: 1  # evaluate every n checkpoints, for speed
batch_size: 64
num_workers: 10

# Denoiser options
denoiser_train_dir:
out_dir: ${denoiser_train_dir}/eval_fitness_training
checkpoint_override: null

# Data options for overriding denoiser config (null values default to denoiser config)
dataset_path: /scratch/hielab/talal/datasets
datasets: ["s669", "fireprot", "fireprot_homologue_free","skempi"]
data:
  pdb_path: null
  fixed_size: 2048
  phase: eval
  overwrite_cache: false
  group_by_exp: false
  scoring_method: single

scn_diffusion:
  # Sidechain diffusion parameters
  num_steps: 20
  timestep_schedule:
    num_steps: ${scn_diffusion.num_steps}
    mode: "linear"
    t_start: 0.0
    t_end: 1.0
  noise_schedule:
    name: "step_scale"
    c: 1.5
  churn_cfg:
    s_churn: 0
    s_noise: 1.0
    s_t_min: 0.01
    s_t_max: 50.0
    num_steps: ${scn_diffusion.num_steps}

# Co-design self-consistency eval options
num_codes_sc_batches: 1

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
