# Wandb configuration
project: "allatom_design"  # Wandb project name
wandb_id: "richardshuai"  # Wandb username
exp_name: null # Wandb exp name
group: "debug" # Wandb group name

# Run settings
no_wandb: false  # Disable wandb logging
seed: 0
start_step: 0  # start evaluation after this epoch, 0 or null to start from the beginning
eval_every_n_ckpts: 1  # evaluate every n checkpoints, for speed
batch_size: 64
num_workers: 10

# Evals to run
run_seq_recovery: true  # compute sequence recovery
run_codes_sc: true  # run self-consistency eval with inverse-folded sequences

# Denoiser options
denoiser_train_dir:
out_dir: ${denoiser_train_dir}/eval_inv_fold_training

# Data options for overriding denoiser config (null values default to denoiser config)
data:
    pdb_path: /media/scratch/datasets/ingraham_cath_dataset
    designability_csv: /media/scratch/datasets/ingraham_cath_dataset/all_esmfold_native_with_cath_gapped_with_tm_with_seq.csv
    n_random_subset: null

subset_length_range: null # only evaluate on sequences within this length range

# Inverse folding options
aatype_decoding_order_mode: "random"
seq_only: true  # true to not pack sidechains during sampling
temperature: 0.1
repack_last: true  # after design, repack the final sequence obtained
psce_threshold: null  # only keep sidechains below this threshold during design; null to keep all
noise_labels: null  # per-residue noise labels, float for same noise for each residue  # TODO: implement user-provided per-residue noise labels

num_steps_list: [50]  # number of denoising steps for inverse folding
timestep_schedule:
  num_steps: null  # will be filled in by num_steps_list
  mode: "linear"
  t_start: 0.0
  t_end: 1.0

scn_diffusion:
  # Sidechain diffusion parameters
  num_steps: 50
  timestep_schedule:
    num_steps: ${scn_diffusion.num_steps}
    mode: "linear"
    t_start: 0.0
    t_end: 1.0
  noise_schedule:
    name: "step_scale"
    c: 1.5
  churn_cfg:
    s_churn: 0
    s_noise: 1.0
    s_t_min: 0.01
    s_t_max: 50.0
    num_steps: ${scn_diffusion.num_steps}

# Co-design self-consistency eval options
num_codes_sc_batches: 1

# Structure prediction model args
struct_pred_cfg:
  model_name: "af2"  # ["esmfold", "af2", "omegafold"]
  af2:
    data_dir: /media/scratch/huang_lab/af2  # directory containing "params/" with af2 model params
    num_models: 1  # only 1 model is currently supported
    sample_models: false  # randomly sample models from the ensemble
    save_best: false
    num_recycles: 3
    use_multimer: false
  esmfold:
    max_tokens_per_batch: 1024
  omegafold:
    num_pseudo_msa: 15
    mask_rate: 0.12
    num_recycle: 2  # performance saturates after around 10 recycles
    deterministic: true
    subbatch_size: null
    cache_file: /media/scratch/huang_lab/cache/omegafold/omegafold.pt

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs