# Wandb configuration
wandb:
  no_wandb: false  # Disable wandb logging
  project: "allatom_design"  # Wandb project name
  wandb_id: "richardshuai"  # Wandb username
  group: "debug" # Wandb group name

# Outputs
exp_name: null  # experiment name; used for wandb and output directory
base_out_dir: ${denoiser_train_dir}/eval_bb_gen_training  # outputs will be saved to base_out_dir/exp_name

# Run settings
seed: 0
start_step: 0  # start evaluation after this epoch, 0 or null to start from the beginning
end_step: null  # end evaluation after this epoch (inclusive), null to evaluate until the end
eval_every_n_ckpts: 1  # evaluate every n checkpoints, for speed
compute_diversity_metrics: true  # whether to compute pairwise TM and clustering metrics

# Denoiser options
denoiser_train_dir:

# Sampling run parameters
length_range: [32, 256]
length_step_size: 4
n_samples_per_length: 8

# Backbone generation options
bb_gen_cfg:
  ckpt_path: null  # overridden with training checkpoint paths
  sampling_cfg: allatom_design/configs/bb_gen/bb_sampling_base.yaml
  overrides:
    num_steps: 500

# Sequence design config
seq_des_cfg:
  # MPNN args
  model_name: "proteinmpnn"  # ["proteinmpnn", "fampnn"]
  proteinmpnn:
    mpnn_cfg: allatom_design/configs/seq_des/proteinmpnn.yaml
    mpnn_params_dir: /media/scratch/huang_lab/allatom_design/model_params/mpnn
    overrides:
      # for proteinmpnn, num seqs per structure will be batch_size * number_of_batches
      batch_size: 1
      number_of_batches: 1
      verbose: false
  fampnn:
    # FAMPNN args
    fampnn_cfg: allatom_design/configs/seq_des/fampnn_inference.yaml
    fampnn_ckpt: /media/scratch/huang_lab/allatom_design/allatom_design/c6_aasd1/checkpoints/ema/sd-step120000-epoch344-ema0.99.ckpt
    overrides:
      batch_size: 16
      num_seqs_per_pdb: 1
      num_steps: 50
      noise_labels: 0.0

# Pairwise TM-scores
pairwise_tm_subsample: 2000  # number of pairs to subsample

# Foldseek clustering analysis
clustering:
  sctm_cutoffs: [0.7, 0.8]
  foldseek_opts:
    alignment_type: 0  # 0 for structure-only
    tmscore_threshold: 0.5
    c: 0.0
    s: 7.5
    cluster_reassign: true

# Structure prediction model args
struct_pred_cfg:
  model_name: "esmfold"
  base_cfg: allatom_design/configs/struct_pred/struct_pred_base.yaml
  # overrides to base config
  af2:
    data_dir: /media/scratch/huang_lab/af2
  esmfold:
    max_tokens_per_batch: 1024

# Dataset for nnTM calculation, path to directory containing PDBs, null to skip nnTM calculation
nntm_dataset: null

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
