# Wandb configuration
project: "allatom_design"
wandb_id: "richardshuai"
exp_name: null
group: "eval_scaffold_debug"

# Run settings
no_wandb: false
seed: 0
start_step: 0
eval_every_n_ckpts: 1
batch_size: 8
num_workers: 8

# Denoiser
denoiser_train_dir:
out_dir: ${denoiser_train_dir}/eval_scaffold_training

# PDB file inputs
pdb_dir: null
pdb_key_list: null  # list of keys to use from the pdb_dir, null to use all .pdb files
pdb_key_ext: "" # if pdb_key_list does not have extensions, add this extension
subset_length_range: [32, 256]  # inclusive
n_subsample: 500  # max number of PDBs to use for evaluation

# Scaffolding options
scaffold_conditioning_types: ["contiguous", "discontiguous", "unconditional"]

# Timesteps, noise schedule
num_steps: 500
timestep_schedule:
  num_steps: ${num_steps}
  mode: "linear"
  t_start: 0.0
  t_end: 1.0

noise_schedule:
  name: "linear"

churn_cfg:
  s_churn: 0
  s_noise: 1.0
  s_t_min: 0.01
  s_t_max: 50.0
  num_steps: ${num_steps}

autoguidance_cfg:
  use_autoguidance: false
  w: 1.0

# Conditioning
cond_labels: null

# Sequence design model for self-consistency
seq_des_cfg:
  model_name: "proteinmpnn"
  proteinmpnn:
    mpnn_cfg: allatom_design/configs/seq_des/proteinmpnn.yaml
    mpnn_params_dir: /media/scratch/huang_lab/allatom_design/model_params/mpnn
    overrides:
      batch_size: 1
      number_of_batches: 1
      verbose: false
  fampnn:
    fampnn_cfg: allatom_design/configs/seq_des/fampnn.yaml
    fampnn_ckpt: /media/scratch/huang_lab/allatom_design/allatom_design/c2_aasd2/post_hoc_ema_ckpts/ema-step300000-std0.220.ckpt
    overrides:
      batch_size: 16
      num_seqs_per_pdb: 1
      num_steps: 50
      noise_labels: 0.0

# Structure prediction model
struct_pred_cfg:
  model_name: "esmfold"
  af2:
    data_dir: /media/scratch/huang_lab/af2
    num_models: 1
    sample_models: true
    num_recycles: 3
    use_multimer: false
  esmfold:
    max_tokens_per_batch: 1024
  omegafold:
    num_pseudo_msa: 15
    mask_rate: 0.12
    num_recycle: 2
    deterministic: true
    subbatch_size: null
    cache_file: /media/scratch/huang_lab/cache/omegafold/omegafold.pt

# nnTM
nntm_dataset: null

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
