seed: 0
out_dir: /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/plots
overwrite_out_dir: true

# Input paths

line_plots:
  input_pkl_files:
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S100_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S100_psce0.3_no_repack_every_step_c0_aasd4/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/proteinmpnn/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/esm3/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/esm_if1/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/lmdesign/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/attnpacker/all_metrics.pkl

  model_names:
    - FAMPNN (0.3Å)
    # - FAMPNN (0.0Å)
    - ProteinMPNN
    - ESM3
    - ESM-IF1
    # - LM-Design
    - AttnPacker

psce_sweep:
  input_pkl_files:
  - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/val_S100_psce0.1_c0_aasd2/all_metrics.pkl
  - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/val_S100_psce0.2_c0_aasd2/all_metrics.pkl
  - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/val_S100_psce0.3_c0_aasd2/all_metrics.pkl
  - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/val_S100_psce0.5_c0_aasd2/all_metrics.pkl
  - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/val_S100_psce1.0_c0_aasd2/all_metrics.pkl

  model_names:
    - 0.1
    - 0.2
    - 0.3
    - 0.5
    - 1.0

iterative_sampling_plots:
  threshold_rmsd_min: 0
  threshold_rmsd_max: 5
  input_pkl_files:
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S1_c0_aasd2/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S10_c0_aasd2/all_metrics.pkl
    # # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S20_c0_aasd2/all_metrics.pkl
    # # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S50_c0_aasd2/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S100_c0_aasd2/all_metrics.pkl
    # # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S200_c0_aasd2/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S300_c0_aasd2/all_metrics.pkl
    # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S500_c0_aasd2/all_metrics.pkl
    # # - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/proteinmpnn/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S1_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S10_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S100_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S300_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
    - /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S500_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl


  model_names:
    - 1 step
    - 10 steps
    # - 20 steps
    # - 50 steps
    - 100 steps
    # - 200 steps
    - 300 steps
    - 500 steps
    # - ProteinMPNN

confidence_plots:
  input_pkl_file: /media/scratch/huang_lab/allatom_design/allatom_design/sc_evals/outputs/S100_psce0.3_no_repack_every_step_c0_aasd2/all_metrics.pkl
  sample_pkl_dir: /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd2/sample_multi/ema-step300000-std0.010/denovo500_S100_psce0.3_no_repack_every_step/sample_pkls

  model_name: FAMPNN (100 steps)


partial_seq_packing_plots:
  input_seq_csvs:
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.1/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.2/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.3/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.4/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.5/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.6/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.7/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.8/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_0.9/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tseq_1.0/scn_metrics.csv

  input_scn_csvs:
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.1/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.2/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.3/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.4/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.5/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.6/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.7/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.8/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_0.9/scn_metrics.csv
    - /media/scratch/huang_lab/allatom_design/allatom_design/c0_aasd4/sidechain_pack/ema-step300000-std0.250/casp13_14_15_tscn_1.0/scn_metrics.csv


hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
