compute_mpnn: false
compute_esm3: true

train_pdb_key_file: /scratch/users/rshuai/datasets/ingraham_cath_dataset/train_pdb_keys.list
eval_pdb_key_file: /scratch/users/rshuai/datasets/ingraham_cath_dataset/eval_pdb_keys.list
eval2_pdb_key_file: /scratch/users/rshuai/datasets/ingraham_cath_dataset/eval2_pdb_keys.list

pdbs_dir: /scratch/users/rshuai/datasets/ingraham_cath_dataset/pdb_store_with_ext

mpnn:
  out_dir: /scratch/users/rshuai/datasets/ingraham_cath_dataset/fpd_embeddings/mpnn

  mpnn_cfg: allatom_design/configs/mpnn/proteinmpnn.yaml
  mpnn_params_dir: /media/scratch/huang_lab/allatom_design/model_params/mpnn
  overrides:
    # num seqs per structure will be batch_size * number_of_batches
    batch_size: 1
    number_of_batches: 1
    verbose: false

esm3:
  out_dir: /scratch/users/rshuai/datasets/ingraham_cath_dataset

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
