# Run settings
seed: 0
overwrite_out_dir: true  # if true, delete existing output directory

# Denoiser options
denoiser_train_dir:
model_type: "atom_denoiser"  # "seq_denoiser" or "atom_denoiser"
out_dir: null  # if null, write to ${denoiser_train_dir}/post_hoc_ema_ckpts

out_step: 500000
out_stds: null # if null, choose based on out_stds_arange instead
out_stds_arange: [0.01, 0.3, 0.01]   # [start, stop, step]

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
