defaults:
  - af3
  - override loss: structure_prediction_with_confidence

_target_: modelhub.trainers.rf3.RF3TrainerWithConfidence

metrics:
  ptm:
    _target_: modelhub.metrics.predicted_error.ComputePTM
  iptm:
    _target_: modelhub.metrics.predicted_error.ComputeIPTM
  count_clashing_chains:
    _target_: modelhub.metrics.clashing_chains.CountClashingChains
