name: allatom_design
channels:
  - conda-forge
  - salilab
  - bioconda
  - defaults
  - pyg
dependencies:
  - python=3.10
  - ca-certificates
  - openssl
  - certifi
  - scipy=1.12.0
  - bioconda::tmalign
  - pyg
  - gemmi
  - rdkit
  - biopython
  - wandb
  - tqdm
  - natsort
  - omegaconf
  - seaborn
  - dssp
  - prody
  - transformers
  - libboost
  - polars
  - foldseek
  - einops
  - pip
  - pip:
    - hydra-core
    - torchtyping
    - dm-tree
    - timm
    - pdb-tools
    - einx
    - jaxtyping
    - environs
    - loguru
    - pdbeccdutils
    - triton
    - fair-esm
    - joblib

