name: dit

defaults:
  - _self_
  - interpolant: edm_interpolant

# Diffusion settings
use_self_conditioning: true
self_cond_p: 0.9
training_batch_size_mult: 1  # batch size multiplier for diffusion module

# Diffusion conditioning
scaffold_module:
  enabled: false  # true to condition on input scaffolds
  pretrained_weights_path: ${pretrained_module_paths.fampnn}
  fampnn:
    n_aatype: ${model.n_aatype}
    use_gvp: false
    n_channel: 128
    n_layers: 5
    k_neighbors: 48
    ablate_noise_labels: false
    init_hV_with_hS: true

    model_type: "sidechain"
    dropout_p: 0.1
    return_embedding: "last"

    gvp:
      out_dim: ${model.denoiser.scaffold_module.fampnn.n_channel}
      node_hidden_dim_scalar: 128
      node_hidden_dim_vector: 16
      edge_hidden_dim_scalar: 512
      edge_hidden_dim_vector: 1
      rotate_out: false
      graph_embedding:
        mpnn_n_channel: ${model.denoiser.scaffold_module.fampnn.n_channel}
        top_k_neighbors: ${model.denoiser.scaffold_module.fampnn.k_neighbors}
        num_positional_embeddings: 16
        n_aatype: ${model.n_aatype}
        remove_edges_without_coords: true
        node_hidden_dim_scalar: ${model.denoiser.scaffold_module.fampnn.gvp.node_hidden_dim_scalar}
        node_hidden_dim_vector: ${model.denoiser.scaffold_module.fampnn.gvp.node_hidden_dim_vector}
        edge_hidden_dim_scalar: ${model.denoiser.scaffold_module.fampnn.gvp.edge_hidden_dim_scalar}
        edge_hidden_dim_vector: ${model.denoiser.scaffold_module.fampnn.gvp.edge_hidden_dim_vector}
      dropout: ${model.denoiser.scaffold_module.fampnn.dropout_p}
      num_encoder_layers: ${model.denoiser.scaffold_module.fampnn.n_layers}

# DiT
dit:
  num_atoms_in: 4
  use_self_conditioning: ${denoiser.use_self_conditioning}
  condition_on_seq: false
  condition_on_scaffold: ${denoiser.scaffold_module.enabled}
  n_aatype: 21
  inf: ${model.inf}

  # Positional encoding
  pos_encoding: rotary_residx    # one of ["absolute", "absolute_residx", "rotary", "rotary_residx"]
  # Conditioning
  cond_label_to_dropout_p:
    # map from condition label to label dropout probability (required for unconditional generation / classifier-free guidance)
    # null to disable conditioning, 0 to disable label dropout
    crop_aug: 0.0

  # QK normalization
  qk_rmsnorm: true

  # Blocks
  depth: 12
  hidden_size: 384
  num_heads: 6
  mlp_dropout: 0.1
  mlp_ratio: 4.0

  # Pair representation
  pair_rep:
    enabled: false
    use_self_conditioning: ${denoiser.use_self_conditioning}
    c_z: 256
    hidden_size: ${denoiser.dit.hidden_size}

    rel_pos:
      c_z: ${denoiser.dit.pair_rep.c_z}
      relpos_k: 32
    distogram:
      # TODO: might want different distogram bins for self-conditioning, like Proteina?
      min_bin: 1.0
      max_bin: 30.0
      no_bins: 65

  # Scaffold conditioning
  scaffolding:
    h_s: ${model.denoiser.scaffold_module.fampnn.n_channel}
    use_h_s: ${denoiser.scaffold_module.enabled}
    use_concat: false


autoguidance:
  enabled: false
  subsample_train_iter_mult: 16  # train with roughly 1/K of the training iterations

  # Config for guiding model; overrides config for DiT
  dit:
    depth: 9
    hidden_size: 288
    num_heads: 6
    mlp_dropout: 0.1
    mlp_ratio: 4.0
