name: dit

defaults:
  - _self_
  - interpolant: edm_interpolant

task: ${model.task}

# Diffusion settings
use_self_conditioning: true
self_cond_p: 0.9
training_batch_size_mult: 1  # batch size multiplier for diffusion module

# DiT
dit:
  num_atoms_in: 4
  use_self_conditioning: ${denoiser.use_self_conditioning}
  n_aatype: 21
  inf: ${model.inf}

  # Positional encoding
  pos_encoding: rotary_residx    # one of ["absolute", "absolute_residx", "rotary", "rotary_residx"]
  # Conditioning
  cond_label_to_dropout_p:
    # map from condition label to label dropout probability (required for unconditional generation / classifier-free guidance)
    # null to disable conditioning, 0 to disable label dropout
    crop_aug: 0.0

  # QK normalization
  qk_rmsnorm: true

  # Blocks
  depth: 12
  hidden_size: 384
  num_heads: 6
  mlp_dropout: 0.1
  mlp_ratio: 4.0


motif_embedder:
  atom_s: 128
  atom_z: 16
  token_s: ${denoiser.dit.hidden_size}
  atoms_per_window_queries: 32
  atoms_per_window_keys: 128
  atom_feature_dim: 389
  atom_encoder_depth: 3
  atom_encoder_heads: 4
  no_atom_encoder: false


autoguidance:
  enabled: false
  subsample_train_iter_mult: 16  # train with roughly 1/K of the training iterations

  # Config for guiding model; overrides config for DiT
  dit:
    depth: 9
    hidden_size: 288
    num_heads: 6
    mlp_dropout: 0.1
    mlp_ratio: 4.0
