name: esm_dit

defaults:
  - _self_
  - interpolant: edm_ca_interpolant

pretrained_ckpt_path: null

hidden_size: 384
n_aatype: 21

# Diffusion settings
use_self_conditioning: true
self_cond_p: 0.9
training_batch_size_mult: 1  # batch size multiplier for diffusion module

# ESM
esm:
  esm_type: "esm2_8M"  # one of ["esm2_8M", "esm2_35M", "esm2_150M", "esm2_650M", "esm2_3B", "esm2_15B"]
  n_tokens_embed: ${denoiser.n_aatype}
  c_s: ${denoiser.hidden_size}

# DiT
dit:
  num_atoms_in: 4
  use_self_conditioning: true
  condition_on_seq: false
  n_aatype: ${denoiser.n_aatype}
  self_cond_p: 0.9
  inf: ${model.inf}

  # Positional encoding
  pos_encoding: rotary_residx  # one of ["absolute", "absolute_residx", "rotary", "rotary_residx"]

  # Conditioning
  cond_label_to_dropout_p:
    # map from condition label to label dropout probability (required for unconditional generation / classifier-free guidance)
    # null to disable conditioning, 0 to disable label dropout
    crop_aug: 0.0
    designability: 0.2

  # QK normalization
  qk_rmsnorm: true

  # Blocks
  depth: 12
  hidden_size: ${denoiser.hidden_size}
  num_heads: 6
  mlp_dropout: 0.1
  mlp_ratio: 4.0

