name: mpnn_dit

defaults:
  - _self_
  - interpolant: edm_interpolant

# Diffusion settings
use_self_conditioning: true
self_cond_p: 0.9
training_batch_size_mult: 1  # batch size multiplier for diffusion module


dit:
  num_atoms_in: 4
  use_self_conditioning: ${denoiser.use_self_conditioning}
  condition_on_seq: false
  n_aatype: 21
  inf: ${model.inf}

  channels_2d: 128

  # Positional encoding
  pos_encoding: rotary_residx  # one of ["absolute", "absolute_residx", "rotary", "rotary_residx"]

  # Conditioning
  cond_label_to_dropout_p:
    # map from condition label to label dropout probability (required for unconditional generation / classifier-free guidance)
    # null to disable conditioning, 0 to disable label dropout
    crop_aug: 0.0
    designability: 0.2
    dataset_source: 0.0

  # QK normalization
  qk_rmsnorm: true

  # Blocks
  depth: 12
  hidden_size: 384
  num_heads: 6
  mlp_dropout: 0.1
  mlp_ratio: 4.0

  # MPNN encoder denoiser
  mpnn_downsample_factor: 2
  minimpnn_encoder:
    autoregressive: false
    no_aatype_pred: true
    n_aatype: 21
    use_self_conditioning_seq: false
    use_time_cond: true

    n_channel: 128
    n_layers: 3
    k_neighbors: null  # null for fully-connected graph
    noise_cond_mult: 4

    model_type: "protein_mpnn"
    augment_eps: 0.0
    dropout_p: 0.1


# DiT
autoguidance:
  enabled: false
  subsample_train_iter_mult: 16  # train with roughly 1/K of the training iterations

  # Config for guiding model; overrides config for DiT
  dit:
    depth: 9
    hidden_size: 288
    num_heads: 6
    mlp_dropout: 0.1
    mlp_ratio: 4.0
