name: triangle_dit

defaults:
  - _self_
  - interpolant: edm_interpolant

# Diffusion settings
use_self_conditioning: true
self_cond_p: 0.9
training_batch_size_mult: 1  # batch size multiplier for diffusion module


dit:
  num_atoms_in: 4
  use_self_conditioning: ${denoiser.use_self_conditioning}
  condition_on_seq: false
  n_aatype: 21
  inf: ${model.inf}

  channels_2d: 128

  # Positional encoding
  pos_encoding: rotary_residx  # one of ["absolute", "absolute_residx", "rotary", "rotary_residx"]

  # Conditioning
  cond_label_to_dropout_p:
    # map from condition label to label dropout probability (required for unconditional generation / classifier-free guidance)
    # null to disable conditioning, 0 to disable label dropout
    crop_aug: 0.0
    designability: 0.2
    dataset_source: 0.0

  # QK normalization
  qk_rmsnorm: true

  # Blocks
  depth: 12
  hidden_size: 384
  num_heads: 6
  mlp_dropout: 0.1
  mlp_ratio: 4.0

  # Self-conditioning pair stack
  self_cond_pair_stack:
    channels_2d: ${model.denoiser.dit.channels_2d}

    relative_positional_encoding:
      c_z: ${model.denoiser.dit.channels_2d}
      relpos_k: 32
    structure_embedder:
      distogram:
        min_bin: 1.0
        max_bin: 50.0
        no_bins: 51
      embedder_2d:
        n_bins: ${..distogram.no_bins}
        c_z: ${model.denoiser.dit.channels_2d}
        pair_stack:
          n_blocks: 2
          c_z: ${model.denoiser.dit.channels_2d}
          eps: ${model.eps}
          pair_stack_block: ${model.denoiser.dit.self_cond_pair_stack.pair_stack_block}

    pair_stack_block:
      c_z: ${model.denoiser.dit.channels_2d}
      use_tri_mul: false
      tri_mul_first: false
      c_hidden_tri_att: 16
      n_heads: 4
      c_hidden_tri_mul: 64
      pair_transition_n: 2
      dropout_rate: 0.
      inf: ${model.inf}

  distogram_head:
    c_z: ${model.denoiser.dit.channels_2d}
    no_bins: 64


# DiT
autoguidance:
  enabled: false
  subsample_train_iter_mult: 16  # train with roughly 1/K of the training iterations

  # Config for guiding model; overrides config for DiT
  dit:
    depth: 9
    hidden_size: 288
    num_heads: 6
    mlp_dropout: 0.1
    mlp_ratio: 4.0
