# PLINDER is a subset of the PDB, so we inherit from the base PDB config

defaults:
  - base

dataset:
  dataset_parser:
    _target_: datahub.datasets.parsers.InterfacesDFParser
    base_dir: /projects/ml/frozen_pdb_copies/2025_07_13_pdb
  dataset:
    name: plinder
    data: ${paths.data.pdb_data_dir}/interfaces_df_train_plinder.parquet
    filters:
      # filters common across all PDB datasets
      - "deposition_date < '2024-01-01'"
      - "resolution < 9.0"
      - "num_polymer_pn_units <= 300" 
      # interface-specific filters
      - "~(pn_unit_1_non_polymer_res_names.notnull() and pn_unit_1_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
      - "~(pn_unit_2_non_polymer_res_names.notnull() and pn_unit_2_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
    columns_to_load:
      # columns common across all PDB datasets
      - example_id
      - pdb_id
      - assembly_id
      - deposition_date
      - resolution
      - num_polymer_pn_units
      - method
      - n_prot
      - n_nuc
      - n_ligand
      - n_peptide
      - total_num_atoms_in_unprocessed_assembly
      # interface specific columns
      - pn_unit_1_iid
      - pn_unit_2_iid
      - pn_unit_1_non_polymer_res_names
      - pn_unit_2_non_polymer_res_names
      - is_inter_molecule
      - all_pn_unit_iids_after_processing
      - involves_loi
      - pli_qcov__50__strong__component
      - pli_qcov__70__strong__component
      - pli_qcov__50__weak__component
      - pli_qcov__70__weak__component
  transform:
    # interface-specific Transform pipeline parameters
    crop_contiguous_probability: 0.0
    crop_spatial_probability: 1.0
  
weights:
  _target_: datahub.samplers.calculate_weights_by_inverse_cluster_size
  cluster_column: pli_qcov__50__weak__component # Need to ablate