base_out_dir: out_dir/compare_self_consistency/bvc/

comparisons:
  # y-axis, x-axis
  # - ["chroma_ms0", "chroma"]
  # - ["chroma_ms0_noreg", "chroma"]
  # - ["chroma_ms0", "chroma_ms0_noreg"]
  # - ["chroma_ms0", "s6_a0_t0.7"]
  # - ["chroma_ms0", "aicath_pd90"]
  # - ["chroma", "baseline"]
  # - ["baseline", "baseline_noreg"]
  # - ["chroma", "s6_a0_t0.7"]
  # - ["chroma", "aicath_pd90"]
  # - ["baseline", "s6_a0_t0.7"]
  # - ["s6_a0_t0.7", "md_cath_pd90"]
  # - ["md_cath_pd90", "aicath_pd90"]
  # - ["aicath_pd90", "aicath_pd110_ode"]
  # - ["baseline", "eps0.3"]
  # - ["sd3_a8_S_25k", "sd3_a8_S_100k"]
  # - ["sd3_a8_L_25k", "sd3_a8_L_100k"]
  # - ["sd3_a8_S_25k", "sd3_a8_L_25k"]
  # - ["sd3_a8_S_100k", "sd3_a8_L_100k"]
  # - ["sd4_a0_eps0.1_pd80", "sd4_a0_eps0.2_pd80"]
  # - ["sd4_a0_eps0.1_pd80", "sd4_a0_eps0.4_pd80"]
  # - ["sd4_a0_eps0.2_pd80", "sd4_a0_eps0.4_pd80"]
  # - ["sd4_a0_eps0.4_pd70", "sd4_a0_eps0.4_pd100"]
  # - ["aicath_pd90", "sd3_a8_ens7_nc4"]
  # - ["aicath_pd90", "sd3_a8_ens7_nc8"]
  # - ["aicath_pd90", "sd3_a8_ens7_nc16"]
  # - ["aicath_pd90", "sd3_a8_ens8_nc4"]
  # - ["aicath_pd90", "sd3_a8_ens8_nc8"]
  # - ["aicath_pd90", "sd3_a8_ens8_nc16"]
  # - ["sd3_a8_ens7_nc8", "sd3_a8_ens8_nc8"]
  # - ["sd3_a8_ens7_nc16", "sd3_a8_ens8_nc16"]
  # - ["chroma", "sd3_a8_ens8_nc16"]
  - ["baseline", "sd3_a8_ens8_nc16"]

  # # relax_db comparisons
  # - ["sd3_a8_ens4_baseline", "sd3_a8_ens4_s6_a0"]
  # - ["sd3_a8_ens4_baseline", "sd3_a8_ens4_spd0_a3_cfg2_700K"]
  # - ["sd3_a8_ens4_s6_a0", "sd3_a8_ens4_spd0_a3_cfg2_700K"]

model_csvs:
  - model_name: "chroma"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma/chroma_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma"

  - model_name: "chroma_ms0"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma_ms0/chroma_ms0_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma, multistate + LCP regularization"

  - model_name: "chroma_ms0_noreg"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma_ms0_noreg/chroma_ms0_noreg_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma, multistate + no regularization"

  - model_name: "baseline"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps500_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Baseline"

  - model_name: "baseline_noreg"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps5000_noreg_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Baseline, no reg"

  # s6_a0 models
  - model_name: "s6_a0_t0.7"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep2_t0.7_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "s6_a0, t=0.7"

  # MD-CATH models
  - model_name: "md_cath_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep4_pd90_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "MD-CATH, pd90"

  - model_name: "md_cath_pd110_ode"
    csv: null
    plot_name: "MD-CATH, pd110, ODE"

  # AI-CATH models
  - model_name: "aicath_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep6_pd90_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90"

  - model_name: "aicath_pd110_ode"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep7_pd110_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd110, ODE"

  - model_name: "aicath_pd90_no_primary"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep9_idx11_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no primary conformer"

  # Gaussian noise only
  - model_name: "eps0.1"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.1_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.1"
  - model_name: "eps0.3"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.3_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.3"
  - model_name: "eps0.5"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.5_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.5"

  # compare regularization with multistate
  - model_name: "aicath_pd90_noreg_ps500"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx0_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no regularization, 500 sweeps"
  - model_name: "aicath_pd90_noreg_ps5000"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx1_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no regularization, 5000 sweeps"
  - model_name: "aicath_pd90_LCP_ps500"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx2_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, LCP regularization, 500 sweeps"
  - model_name: "aicath_pd90_LCP_ps5000"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, LCP regularization, 5000 sweeps"

  # sd3_a8_ens0: check scaling and checkpoints
  - model_name: "sd3_a8_S_25k"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens0/sd3_a8_ens0_idx0_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, 25k steps"
  - model_name: "sd3_a8_S_100k"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens0/sd3_a8_ens0_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, 50k steps"
  - model_name: "sd3_a8_L_25k"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens0/sd3_a8_ens0_idx4_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_L, 25k steps"
  - model_name: "sd3_a8_L_100k"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens0/sd3_a8_ens0_idx7_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_L, 100k steps"

  # sd4_a0_ens0: compare models trained with different amounts of gaussian noise
  - model_name: "sd4_a0_eps0.1_pd70"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx0_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.1, aicath pd=70"
  - model_name: "sd4_a0_eps0.1_pd80"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx1_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.1, aicath pd=80"
  - model_name: "sd4_a0_eps0.1_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx2_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.1, aicath pd=90"
  - model_name: "sd4_a0_eps0.1_pd100"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.1, aicath pd=100"
  - model_name: "sd4_a0_eps0.2_pd70"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx5_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.2, aicath pd=70"
  - model_name: "sd4_a0_eps0.2_pd80"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx6_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.2, aicath pd=80"
  - model_name: "sd4_a0_eps0.2_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx7_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.2, aicath pd=90"
  - model_name: "sd4_a0_eps0.2_pd100"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx8_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.2, aicath pd=100"
  - model_name: "sd4_a0_eps0.4_pd70"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx10_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.4, aicath pd=70"
  - model_name: "sd4_a0_eps0.4_pd80"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx11_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.4, aicath pd=80"
  - model_name: "sd4_a0_eps0.4_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx12_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.4, aicath pd=90"
  - model_name: "sd4_a0_eps0.4_pd100"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd4_a0_ens0/sd4_a0_ens0_idx13_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd4_a0, eps=0.4, aicath pd=100"

  # relax_db models (sd3_a8_ens4)
  - model_name: "sd3_a8_ens4_baseline"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens4/sd3_a8_ens4_idx0_af2pdbs_relaxdb_initial/self_consistency_metrics.csv
    plot_name: "af2pdbs_relaxdb, baseline"
  - model_name: "sd3_a8_ens4_s6_a0"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens4/sd3_a8_ens4_idx1_af2pdbs_relaxdb_initial/self_consistency_metrics.csv
    plot_name: "af2pdbs_relaxdb, s6_a0"
  - model_name: "sd3_a8_ens4_spd0_a3_cfg2_700K"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens4/sd3_a8_ens4_idx3_af2pdbs_relaxdb_initial/self_consistency_metrics.csv
    plot_name: "af2pdbs_relaxdb, partial diffusion ensemble"
    
  # sum-aggregated potts models (sd3_a8_ens7)
  - model_name: "sd3_a8_ens7_nc4"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens7/sd3_a8_ens7_idx2_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, sum, nc=4"
  - model_name: "sd3_a8_ens7_nc8"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens7/sd3_a8_ens7_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, sum, nc=8"
  - model_name: "sd3_a8_ens7_nc16"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens7/sd3_a8_ens7_idx4_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, sum, nc=16"

  # mean-aggregated potts models (sd3_a8_ens8)
  - model_name: "sd3_a8_ens8_nc4"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens8/sd3_a8_ens8_idx2_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, mean, nc=4"
  - model_name: "sd3_a8_ens8_nc8"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens8/sd3_a8_ens8_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, mean, nc=8"
  - model_name: "sd3_a8_ens8_nc16"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/ensemble_design/sd3_a8_ens8/sd3_a8_ens8_idx4_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "sd3_a8_S, mean, nc=16"

# Which models that need to use subset_pdb_names
subset_pdb_names: /media/scratch/datasets/boltz_val_cifs/pdb_name_lists/protein_monomer_32_256_no_ligand.txt

use_subset_models:
  - s6_a0_t0.7

# Add lengths
# length_csv: null
length_csv: /media/scratch/datasets/boltz_val_cifs/length_lists/protein_monomer_32_512_no_ligand.csv
length_legend_range: [32, 512]

# Add secondary structure annotations
sse_pt: null
# sse_pt: /media/scratch/datasets/boltz_val_cifs/sse_anno/protein_monomer_32_512_no_ligand.pt

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
