# out_dir: out_dir/compare_self_consistency/bvc_chroma_vs_atommpnn
# out_dir: out_dir/compare_self_consistency/bvc_chroma_vs_ms_sweep2_t0.7
# out_dir: out_dir/compare_self_consistency/bvc_baseline_vs_ms_sweep2_t0.7
out_dir: out_dir/compare_self_consistency/bvc_noreg_baseline_vs_ms_sweep2_t0.7


# model1_boltz_csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma/chroma_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
# model1_boltz_csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps500_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
model1_boltz_csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps5000_noreg_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv

model2_boltz_csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep2_t0.7_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
# model2_boltz_csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps500_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv

# model1_name: "Chroma"
# model1_name: "(500 sweeps, LCP regularization)"
model1_name: "(5000 sweeps, no reg)"

model2_name: "(5000 sweeps, no reg, t=0.7)"

subset_pdb_names: /media/scratch/datasets/boltz_val_cifs/pdb_name_lists/protein_monomer_32_256_no_ligand.txt

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
