base_out_dir: out_dir/compare_self_consistency/bvc/

comparisons:
  # y-axis, x-axis
  # - ["chroma_ms0", "chroma"]
  # - ["chroma_ms0_noreg", "chroma"]
  # - ["chroma_ms0", "chroma_ms0_noreg"]
  # - ["chroma_ms0", "s6_a0_t0.7"]
  # - ["chroma_ms0", "aicath_pd90"]
  # - ["chroma", "baseline"]
  # - ["baseline", "baseline_noreg"]
  # - ["chroma", "s6_a0_t0.7"]
  # - ["chroma", "aicath_pd90"]
  # - ["baseline", "s6_a0_t0.7"]
  # - ["s6_a0_t0.7", "md_cath_pd90"]
  # - ["md_cath_pd90", "aicath_pd90"]
  # - ["aicath_pd90", "aicath_pd110_ode"]
  # - ["baseline", "eps0.3"]
  # - ["baseline_noreg", "eps0.3"]
  # - ["s6_a0_t0.7", "eps0.3"]
  # - ["eps0.1", "eps0.3"]
  # - ["eps0.3", "eps0.5"]
  # - ["eps0.3", "aicath_pd90"]
  # - ["baseline", "aicath_pd90"]
  # - ["s6_a0_t0.7", "aicath_pd90"]
  # - ["eps0.5", "aicath_pd90"]
  # - ["eps0.5", "s6_a0_t0.7"]
  # - ["eps0.3", "s6_a0_t0.7"]
  # - ["aicath_pd90", "aicath_pd90_no_primary"]
  # - ["aicath_pd90_noreg_ps500", "aicath_pd90_LCP_ps500"]
  # - ["aicath_pd90_noreg_ps5000", "aicath_pd90_LCP_ps500"]
  # - ["chroma", "aicath_pd90_LCP_ps500"]
  # - ["chroma", "aicath_pd90_LCP_ps5000"]
  # - ["aicath_pd90_LCP_ps500", "aicath_pd90_LCP_ps5000"]
  - ["aicath_pd90_LCP_ps500", "baseline"]

model_csvs:
  - model_name: "chroma"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma/chroma_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma"

  - model_name: "chroma_ms0"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma_ms0/chroma_ms0_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma, multistate + LCP regularization"

  - model_name: "chroma_ms0_noreg"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/boltz_val_cifs_evals/protein_monomer_32_512_no_ligand/chroma_ms0_noreg/chroma_ms0_noreg_bvc_protein_monomer_32_512_no_ligand_boltz1/sc_metrics.csv
    plot_name: "Chroma, multistate + no regularization"

  - model_name: "baseline"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps500_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Baseline"

  - model_name: "baseline_noreg"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_baseline_ps5000_noreg_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Baseline, no reg"

  # s6_a0 models
  - model_name: "s6_a0_t0.7"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep2_t0.7_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "s6_a0, t=0.7"

  # MD-CATH models
  - model_name: "md_cath_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep4_pd90_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "MD-CATH, pd90"

  - model_name: "md_cath_pd110_ode"
    csv: null
    plot_name: "MD-CATH, pd110, ODE"

  # AI-CATH models
  - model_name: "aicath_pd90"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep6_pd90_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90"

  - model_name: "aicath_pd110_ode"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep7_pd110_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd110, ODE"

  - model_name: "aicath_pd90_no_primary"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep9_idx11_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no primary conformer"

  # Gaussian noise only
  - model_name: "eps0.1"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.1_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.1"
  - model_name: "eps0.3"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.3_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.3"
  - model_name: "eps0.5"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep8_eps0.5_nc16_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "Gaussian noise, eps=0.5"

  # compare regularization with multistate
  - model_name: "aicath_pd90_noreg_ps500"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx0_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no regularization, 500 sweeps"
  - model_name: "aicath_pd90_noreg_ps5000"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx1_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, no regularization, 5000 sweeps"
  - model_name: "aicath_pd90_LCP_ps500"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx2_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, LCP regularization, 500 sweeps"
  - model_name: "aicath_pd90_LCP_ps5000"
    csv: /media/scratch/huang_lab/allatom_design/allatom_design/sd3_a2_cfg1/multistate_sweep/sd3_a2_cfg1_ms_sweep10_idx3_bvc_protein_monomer_32_512_no_ligand_boltz1/self_consistency_metrics.csv
    plot_name: "AI-CATH, pd90, LCP regularization, 5000 sweeps"


# Which models that need to use subset_pdb_names
subset_pdb_names: /media/scratch/datasets/boltz_val_cifs/pdb_name_lists/protein_monomer_32_256_no_ligand.txt

use_subset_models:
  - s6_a0_t0.7

# Add lengths
length_csv: /media/scratch/datasets/boltz_val_cifs/length_lists/protein_monomer_32_512_no_ligand.csv
length_legend_range: [32, 512]

# Add secondary structure annotations
sse_pt: /media/scratch/datasets/boltz_val_cifs/sse_anno/protein_monomer_32_512_no_ligand.pt

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
