base_out_dir: out_dir/plot_farfalle_bindcraft_evals/bindcraft_exp1
sampling_results_dir: /media/scratch/huang_lab/farfalle/sampling_results/bindcraft_exp1

comparisons:
  # all cc95 epochs
  # - name: "cc95_epochs"
  #   models: ["cc95_epoch2700", "cc95_epoch2750", "cc95_epoch2800", "cc95_epoch2850", "cc95_epoch2900", "cc95_epoch2950", "cc95_epoch3000", "cc95_epoch3050", "cc95_epoch3100", "cc95_epoch3150", "cc95_epoch3200", "cc95_epoch3250", "cc95_epoch3300", "cc95_epoch3350", "cc95_epoch3400", "cc95_epoch3450"]

  # cc95 vs. cc83
  - name: "cc95_vs_cc83"
    models: ["cc95_epoch3450", "cc83_epoch2616"]


model_csvs:
  - model_name: "cc74_epoch1000"
    csv: ${sampling_results_dir}/cc74-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc74-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc74, epoch1000"

  - model_name: "cc74_epoch1095"
    csv: ${sampling_results_dir}/cc74-epoch1095-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc74-epoch1095-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc74, epoch1095"

  - model_name: "cc75_epoch1000"
    csv: ${sampling_results_dir}/cc75-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc75-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc75, epoch1000"

  - model_name: "cc75_epoch1115"
    csv: ${sampling_results_dir}/cc75-epoch1115-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc75-epoch1115-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc75, epoch1115"

  - model_name: "cc78_epoch1000"
    csv: ${sampling_results_dir}/cc78-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc78-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc78, epoch1000"

  - model_name: "cc78_epoch1431"
    csv: ${sampling_results_dir}/cc78-epoch1431-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc78-epoch1431-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc78, epoch1431"

  - model_name: "cc79_epoch1000"
    csv: ${sampling_results_dir}/cc79-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc79-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc79, epoch1000"

  - model_name: "cc79_epoch2061"
    csv: ${sampling_results_dir}/cc79-epoch2061-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc79-epoch2061-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc79, epoch2061"

  - model_name: "cc80_epoch1000"
    csv: ${sampling_results_dir}/cc80-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc80-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc80, epoch1000"

  - model_name: "cc80_epoch1252"
    csv: ${sampling_results_dir}/cc80-epoch1252-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc80-epoch1252-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc80, epoch1252"

  # - model_name: "cc81_epoch1000"
  #   csv: ${sampling_results_dir}/cc81-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc81-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
  #   plot_name: "cc81, epoch1000"

  - model_name: "cc81_epoch1377"
    csv: ${sampling_results_dir}/cc81-epoch1377-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc81-epoch1377-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc81, epoch1377"

  - model_name: "cc82_epoch1377"
    csv: ${sampling_results_dir}/cc82-epoch1377-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc82-epoch1377-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc82, epoch1377"

  - model_name: "cc83_epoch1000"
    csv: ${sampling_results_dir}/cc83-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc83-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc83, epoch1000"

  - model_name: "cc83_epoch2616"
    csv: /media/scratch/huang_lab/farfalle/sampling_results/bindcraft_exp0_fix_pos/cc83-epoch2616-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc83-epoch2616-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc83, epoch2616"

  - model_name: "cc84_epoch1000"
    csv: ${sampling_results_dir}/cc84-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc84-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc84, epoch1000"

  - model_name: "cc84_epoch2431"
    csv: ${sampling_results_dir}/cc84-epoch2431-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc84-epoch2431-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc84, epoch2431"

  - model_name: "cc85_epoch1000"
    csv: ${sampling_results_dir}/cc85-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc85-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc85, epoch1000"

  - model_name: "cc85_epoch2541"
    csv: ${sampling_results_dir}/cc85-epoch2541-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc85-epoch2541-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc85, epoch2541"

  - model_name: "cc86_epoch1000"
    csv: ${sampling_results_dir}/cc86-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc86-epoch1000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc86, epoch1000"

  - model_name: "cc86_epoch1586"
    csv: ${sampling_results_dir}/cc86-epoch1586-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc86-epoch1586-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc86, epoch1586"

  # cc95
  - model_name: "cc95_epoch2700"
    csv: ${sampling_results_dir}/cc95-epoch2700-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2700-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2700"
  - model_name: "cc95_epoch2750"
    csv: ${sampling_results_dir}/cc95-epoch2750-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2750-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2750"
  - model_name: "cc95_epoch2800"
    csv: ${sampling_results_dir}/cc95-epoch2800-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2800-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2800"
  - model_name: "cc95_epoch2850"
    csv: ${sampling_results_dir}/cc95-epoch2850-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2850-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2850"
  - model_name: "cc95_epoch2900"
    csv: ${sampling_results_dir}/cc95-epoch2900-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2900-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2900"
  - model_name: "cc95_epoch2950"
    csv: ${sampling_results_dir}/cc95-epoch2950-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch2950-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch2950"
  - model_name: "cc95_epoch3000"
    csv: ${sampling_results_dir}/cc95-epoch3000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3000-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3000"
  - model_name: "cc95_epoch3050"
    csv: ${sampling_results_dir}/cc95-epoch3050-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3050-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3050"
  - model_name: "cc95_epoch3100"
    csv: ${sampling_results_dir}/cc95-epoch3100-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3100-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3100"
  - model_name: "cc95_epoch3150"
    csv: ${sampling_results_dir}/cc95-epoch3150-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3150-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3150"
  - model_name: "cc95_epoch3200"
    csv: ${sampling_results_dir}/cc95-epoch3200-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3200-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3200"
  - model_name: "cc95_epoch3250"
    csv: ${sampling_results_dir}/cc95-epoch3250-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3250-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3250"
  - model_name: "cc95_epoch3300"
    csv: ${sampling_results_dir}/cc95-epoch3300-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3300-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3300"
  - model_name: "cc95_epoch3350"
    csv: ${sampling_results_dir}/cc95-epoch3350-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3350-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3350"
  - model_name: "cc95_epoch3400"
    csv: ${sampling_results_dir}/cc95-epoch3400-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3400-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3400"
  - model_name: "cc95_epoch3450"
    csv: ${sampling_results_dir}/cc95-epoch3450-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0/cc95-epoch3450-sampling_sidechain_conditional-autoguidance-None-ss1.2-schurn200-reconcustom10.0-cfg1.0-ccstart0.0-dx0.0-dy0.0-dz0.0_metrics.csv
    plot_name: "cc95, epoch3450"

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
