base_out_dir: out_dir/bindcraft_traj_benchmark

comparisons:
  # y-axis, x-axis
  - ["ours", "mpnn"]
  - ["ours", "ensemble"]
  - ["ensemble", "mpnn"]
  - ["ours_rmseqF_rmscF", "mpnn_rmseqF_rmscF"]
  - ["mpnn", "mpnn_rmseqF_rmscF"]

model_csvs:
  - model_name: "ours"
    csv: "/media/scratch/huang_lab/allatom_design/allatom_design/bindcraft_traj_benchmark/bc0/bc0_idx0/self_consistency_metrics.csv"
    plot_name: "Ours (Soluble Potts)"

  - model_name: "mpnn"
    csv: "/media/scratch/huang_lab/allatom_design/allatom_design/bindcraft_traj_benchmark/bc0/bc0_idx1/self_consistency_metrics.csv"
    plot_name: "SolubleMPNN"

  - model_name: "ensemble"
    csv: "/media/scratch/huang_lab/allatom_design/allatom_design/bindcraft_traj_benchmark/bc0/bc0_idx2/self_consistency_metrics.csv"
    plot_name: "Ours (ensembled)"

  - model_name: "ours_rmseqF_rmscF"
    csv: "/media/scratch/huang_lab/allatom_design/allatom_design/bindcraft_traj_benchmark/bc1/bc1_idx0/self_consistency_metrics.csv"
    plot_name: "Ours (Soluble Potts, rmseqF, rmscF)"

  - model_name: "mpnn_rmseqF_rmscF"
    csv: "/media/scratch/huang_lab/allatom_design/allatom_design/bindcraft_traj_benchmark/bc1/bc1_idx1/self_consistency_metrics.csv"
    plot_name: "SolubleMPNN (rmseqF, rmscF)"


hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
