# TODO: Inherit from common config with default Transform pipeline

multidomain_distillation:
  dataset:
    _target_: modelhub.data.paired_msa.MultiInputDatasetWrapper
    save_failed_examples_to_dir: null

    # cif parser
    cif_parser_args:
      #assume_residues_all_resolved: true
      cache_dir: null
      load_from_cache: false
      save_to_cache: false 

    # metadata parser
    dataset_parser:
      _target_: modelhub.data.paired_msa.MultidomainDFParser

    # metadata dataset
    dataset:
      _target_: datahub.datasets.datasets.PandasDataset
      name: multidomain_distillation
      id_column: example_id
      data: /projects/ml/datahub/dfs/domain_domain/domain_domain_dataset.DIGS.parquet
      columns_to_load:
        - example_id
        - pdb_path
        - msa_path
    return_key: null
    transform:
      _target_: ${datasets.pipeline_target}
      is_inference: False
      input_contains_explicit_msa: True
      protein_msa_dirs: []
      rna_msa_dirs: []
      n_recycles: ${datasets.n_recycles_train}
      crop_size: ${datasets.crop_size}
      n_msa: ${datasets.n_msa}
      diffusion_batch_size: ${datasets.diffusion_batch_size_train}
      max_atoms_in_crop: ${datasets.max_atoms_in_crop}
      crop_contiguous_probability: 0.25
      crop_spatial_probability: 0.75
      run_confidence_head: ${datasets.run_confidence_head}
      take_first_chiral_subordering: ${datasets.take_first_chiral_subordering}
      use_element_for_atom_names_of_atomized_tokens: ${datasets.use_element_for_atom_names_of_atomized_tokens}
      mirror_prob: 0.0
      atomization_prob: ${datasets.atomization_prob}
      ligand_dropout_prob: 0.0
      p_unconditional: ${datasets.p_unconditional}
      p_dropout_atom_level_embeddings: ${datasets.p_dropout_atom_level_embeddings}
