name: motif_selector

# Probabilities for selecting each motif type
p:
  # Token-level motif selection
  unconditional: 0.25
  protein_contiguous: 0.25
  protein_discontiguous: 0.5


restype_mask_p:
  all: 1.0  # mask out all restypes
  uniform: 0.0  # mask out uniformly

atom_p:
  # Atom-level motif selection
  all: 0.5
  protein_sidechain: 0.0
  protein_backbone: 0.5

# Configs
protein_contiguous:
  max_span_len: 20

protein_discontiguous:
  max_discontiguous_res: 20
  dist_threshold: 12.0
