base_out_dir: out_dir/plot_eval_cfold

# A list of evaluation directories to process
eval_dirs:
  - path: /media/scratch/huang_lab/allatom_design/allatom_design/eval_cfold/sd4_a5_cfold/sd4_a5_cfold_idx_cfold_boltz1
    plot_name: "sd4_a5_cfold"


# optional manifest csv for plotting lengths
manifest_csv: /media/scratch/datasets/cfold/manifest.csv
length_legend_range: [32, 256] # Optional: set min/max for colorbar

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
