# Wandb configuration
project: "allatom_design"  # Wandb project name
wandb_id: "richardshuai"  # Wandb username
group: "debug" # Wandb group name
no_wandb: false

# Sampling run settings
ad_ckpt:
sd_ckpt:

cuda: true
num_workers: 10
out_dir: null  # null to save in the atom denoiser model run directory
exp_name: baseline  # sampling experiment name
overwrite_out_dir: true  # if true, delete existing output directory
seed: 0
batch_size: 64

# Evaluation mode
length_bin_size: 50  # bin lengths into intervals of this size for evaluation, starting from 0

# Sampling run parameters
length_range: [50,100]
length_step_size: 10
n_samples_per_length: 2
n_traj_per_length: 0  # number of trajectories to save per length
limit_traj_steps: 5  # limit the number of steps we save in a trajectory (evenly spaced)
traj_conect: false
align_traj_to_last_step: true  # whether to align trajectories to the last step

# Sampling hyperparameters
joint:
  # All-atom model sampling parameters
  num_steps: 5
  sd:
    timestep_schedule:
      num_steps: ${joint.num_steps}
      mode: "linear"
      t_start: 0.0
      t_end: 1.0
  ad:
    timestep_schedule:
      num_steps: ${joint.num_steps}
      mode: "linear"
      t_start: 0.0
      t_end: 1.0

ad:
  # Atom denoiser sampling parameters
  num_steps: 500
  timestep_schedule:
    num_steps: ${ad.num_steps}
    mode: "linear"
    t_start: 0.0
    t_end: 1.0
  noise_schedule:
    name: "linear"
  churn_cfg:
    s_churn: 0
    s_noise: 1.0
    s_t_min: 0.01
    s_t_max: 50.0
    num_steps: ${ad.num_steps}

  # Autoguidance
  autoguidance_cfg:
    use_autoguidance: false
    w: 1.0

sd:
  # Sequence denoiser sampling parameters
  seq:
    aatype_decoding_order_mode: "random"
    num_corrector_steps: 0
    corrector_step_ratio: 0.5
    num_steps: 2
    timestep_schedule:
      num_steps: ${sd.seq.num_steps}
      mode: "linear"
      t_start: 0.0
      t_end: 1.0
  scd:
    num_steps: 50
    timestep_schedule:
      num_steps: ${sd.scd.num_steps}
      mode: "linear"
      t_start: 0.0
      t_end: 1.0
    noise_schedule:
      name: "step_scale"
      c: 1.5
    churn_cfg:
      s_churn: 0
      s_noise: 1.0
      s_t_min: 0.01
      s_t_max: 50.0
      num_steps: ${sd.scd.num_steps}


cond_labels: null

# Self-consistency evaluation
sc:
  run_codes_sc: true  # run co-design self-consistency eval
  run_codes_sc_intermediate: true  # run co-design self-consistency eval for intermediate steps
  bin_range: [0, 500]  # only evaluate structures for length bins that start in this range (inclusive)
  max_samples_per_bin: 100  # maximum number of samples to evaluate per length bin

# Dataset for nnTM calculation, path to directory containing PDBs
nntm_dataset: /media/scratch/datasets/ingraham_cath_dataset/pdb_store_renumbered

# Pairwise TM-scores
pairwise_tm_subsample: 1000  # number of pairs to subsample

# Foldseek clustering analysis
clustering:
  sctm_cutoffs: [0.7, 0.8]
  foldseek_opts:
    alignment_type: 2  # 0 for structure-only; 2 for sequence-structure
    tmscore_threshold: 0.5
    c: 0.0
    s: 7.5
    cluster_reassign: true

# Secondary structure KL divergence
ss_kld:
  dssp_csv: /media/scratch/datasets/ingraham_cath_dataset/dssp/dssp_length_strict.csv
  bin_size: 10  # size of secondary structure percentage bins
  pseudocount: 0.01  # pseudocount for KL divergence calculation; set arbitrarily to 0.01


# Structure prediction model args
struct_pred_cfg:
  model_name: "esmfold"  # ["esmfold", "af2", "omegafold"]
  af2:
    data_dir: /media/scratch/huang_lab/af2  # directory containing "params/" with af2 model params
    num_models: 1  # only 1 model is currently supported
    sample_models: true  # randomly sample models from the ensemble
    num_recycles: 3
    use_multimer: false
  esmfold:
    max_tokens_per_batch: 1024
  omegafold:
    num_pseudo_msa: 15
    mask_rate: 0.12
    num_recycle: 2  # performance saturates after around 10 recycles
    deterministic: true
    subbatch_size: null
    cache_file: /media/scratch/huang_lab/cache/omegafold/omegafold.pt


hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
