# Run settings
seed: 0
num_workers: 8  # for dataloading

# Inputs
ckpt_path: null
out_dir: null

# PDB file inputs
conformer_dir: null
sample_dir: null

# PDB file processing
pdb_processing_cfg:
  num_workers: ${num_workers}

  # if we have to convert PDBs to mmCIFs
  pdb_to_cif_conversion_cfg:
    assign_label_seq_id: false  # if true, automatically assign label_seq_id by aligning the sequence in the model with the sequence in the SEQRES
    set_seqid_gaps_to_X: true  # if true, set seqid gaps to X

  # CCD
  ccd_cfg:
    use_redis: true

    # If using redis (fast)
    ccd_rdb_path: allatom_design/data/ccd.rdb  # path to the chemical component dictionary rdb file

    # If redis host is null, use this path instead to load the chemical component dictionary (can be much slower)
    ccd_pkl_path: /media/scratch/datasets/boltz/ccd.pkl


# Sampling config
sampling_cfg_overrides:
  batch_size: 16
  num_workers: ${num_workers}

seq_des_cfg:
  model_name: "atom_mpnn"
  atom_mpnn:
    ckpt_path: ${ckpt_path}
    sampling_cfg: allatom_design/configs/seq_des/atom_mpnn_inference.yaml
    overrides: ${sampling_cfg_overrides}

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
