defaults:
  - _self_

sweep_prefix: "cfg_"

num_steps: [500]
use_churn: [false]  # cannot be null, must override sampling config

s_churn: null
s_noise: null

step_scale: null

cond_labels:
  # - {designability: "DESIGNABLE"}
  # - {designability: "UNDESIGNABLE"}
  # - {}

use_classifier_free_guidance: [false, true]  # cannot be null, must override sampling config
cfg_w: [0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 10.0]


hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
