name: sd3_rf

training_t_schedule: "proteina"  # "logit_normal", "mode", "proteina"

training_t_schedule_cfg:
  logit_normal:
    # mean and std of the normal distribution
    location: 0
    scale: 1
  mode:
    s: 0  # between -1 and 2 / (pi - 2)
  proteina:
    alpha: 1.9
    beta: 1.0
