# Redesign pocket sequence config
# This config is for evaluating pre-designed samples from CaliBy codebase

########### Basic settings #########

# Wandb settings
wandb:
  no_wandb: true  # Disable wandb logging
  project: "ligand_seq_des"
  wandb_id: "zhkim216"  # Wandb username
  group: null

# Basic settings
debug: true
num_debug_samples: 1
evaluate_self_consistency: true
seed: 0
num_workers: 8 # for dataloading
start_step: 15000  # start evaluation after this step, 0 or null to start from the beginning
end_step: 22500  # end evaluation after this step (inclusive), null to evaluate until the end
eval_every_n_ckpts: 1  # evaluate every n checkpoints, for speed
eval_last_ckpt: false
use_ema: false

# Metadata
metadata_path: /home/possu/jinho/datasets/atomworks_lmpnn_valset_filtered_re/interface_df_total.parquet

# Outputs
exp_name: redesign_with_lcaliby_5.0 # experiment name; used for wandb and output directory
base_out_dir: /home/possu/jinho/allatom-design/local_debug_output/251231

# Cached examples (original structures with ligands)
cached_example_path: /home/possu/jinho/datasets/atomworks_lmpnn_valset_filtered/cached_examples

# Redesign pocket sequence options
redesign_cfg:
  redesign_pocket_seq: true
  use_native_pocket_seq: true #! If false, automatically redesign the pocket sequence using lcaliby
  pocket_distance: 5.0

# Docking metrics configuration
docking_metrics_cfg:
  pocket_distance_for_metrics: 8.0

######### Data & Transform configurations #########
# Configurations for getting designed structures' paths
pdb_cfg:
  pdb_dir: /home/possu/jinho/allatom-design/debug/251230_caliby_wocenter_samples/samples
  pdb_name_list: null  # null to use all files in pdb_dir
  pdb_name_ext: ".cif"
  n_subsample: null  # null to use all samples

# Data configuration for loading designed structures
data_cfg_for_design:
  cif_parser_args:
    add_missing_atoms: true
    remove_waters: true
    remove_ccds: []
    fix_ligands_at_symmetry_centers: true
    fix_arginines: true
    convert_mse_to_met: true
    hydrogen_policy: "remove"
    extra_fields: "all"  

# Transform configuration for featurizing designed structures
transform_cfg_for_design:
  preprocess_cfg:
    undesired_res_names: []
    b_factor_min: null
    b_factor_max: null
    min_residues_for_polymers: 0
    remove_terminal_oxygen_protein: true
    remove_terminal_oxygen_nucleic_acid: true
  featurizer_cfg:
    max_tokens: null
    max_atoms: null
    remove_keys: []    
    remove_unresolved_tokens: true

# Data configuration for loading AF3 predictions (for self-consistency evaluation)
data_cfg_for_af3_prediction:
  use_load_any: false
  cif_parser_args:
    add_missing_atoms: true  # For charge annotation
    remove_waters: false
    remove_ccds: []
    fix_ligands_at_symmetry_centers: false  # Keep AF3's original ligand predictions
    fix_arginines: false
    convert_mse_to_met: false
    hydrogen_policy: "remove"
    extra_fields: []  # AF3 CIF files don't have custom annotations

# Transform configuration for AF3 predictions
transform_cfg_for_af3_prediction:
  featurizer_cfg:
    max_tokens: null
    max_atoms: null
    remove_keys: []
    remove_unresolved_tokens: true  # Remove atoms with NaN coords
  preprocess_cfg:
    undesired_res_names: []
    b_factor_min: null
    b_factor_max: null
    min_residues_for_polymers: 0
    remove_terminal_oxygen_protein: false
    remove_terminal_oxygen_nucleic_acid: false

######### L-Caliby configuration #########
denoiser_train_dir: /home/possu/jinho/out_dir/ligand_seq_des/exp2_cfg2
sampling_cfg_overrides:
  batch_size: 2
  num_seqs_per_pdb: 1  # number of sequences to sample per pdb
  omit_aas: null  # exclude certain aatypes globally, e.g. ["C", "G"]. "X" is always excluded.
  noise_labels: null
  num_workers: ${num_workers}
  use_potts_sampling: true
  ligand_conditioning: true
  potts_sampling_cfg:
    potts_sweeps: 500
    lcp_expand_edge_idx_fix: true

# Positional constraints: supports columns in [pdb_key,fixed_pos_seq,fixed_pos_scn,fixed_pos_override_seq,pos_restrict_aatype]
# e.g. 2fyzA,"A1-100,B1-100","A1-100"
pos_constraint_csv: null
  
# Sequence design config
seq_des_cfg:
  model_name: "lc_atom_mpnn"
  atom_mpnn:
    ckpt_path: null
    sampling_cfg: /home/possu/jinho/allatom-design/allatom_design/configs_local/seq_des/lc_atom_mpnn_inference.yaml
    overrides: ${sampling_cfg_overrides}

######### Structure prediction model configuration (AF3) #########
struct_pred_cfg:
  model_name: "af3"
  af3:
    runner_path: /home/possu/jinho/allatom-design/alphafold3/run_alphafold_debug_local.py
    json_config:
      model_seeds: [42]
      version: 2
    inference_config:
      base:
        model_dir: /home/possu/jinho/model_params/af3
        db_dir: /home/possu/jinho/af3_databases
        flash_attention_implementation: "xla"
      ss:  # Single-sequence prediction config
        num_recycles: 1
        num_diffusion_samples: 1
        max_templates: 0
        ligand_protein_template_conditioning_mode: 0
        mask_template_sidechains: true
        mask_template_sequence: true
      tc:  # Template-conditioned prediction config
        num_recycles: 1
        num_diffusion_samples: 1
        max_templates: 1
        ligand_protein_template_conditioning_mode: 1
        mask_template_sidechains: true
        mask_template_sequence: true
        max_template_date: "2021-09-30"

hydra:
  run:
    dir: /home/possu/jinho/hydra_outputs
