af2:
  data_dir: null
  num_models: 5  # the best by plddt will be saved
  sample_models: true  # whether to randomly sample num_models out of the 5 models
  num_recycles: 3
  use_multimer: false
esmfold:
  max_tokens_per_batch: 1024
