boltz1:
  checkpoint: null
  num_workers: 8
  predict_args:
    recycling_steps: 3
    sampling_steps: 200
    diffusion_samples: 1
    write_confidence_summary: true
    write_full_pae: false
    write_full_pde: false
esmfold:
  max_tokens_per_batch: 1024
