boltz1:
  checkpoint: null
  num_workers: 8
  predict_args:
    recycling_steps: 3
    sampling_steps: 200
    diffusion_samples: 1
    write_confidence_summary: true
    write_full_pae: false
    write_full_pde: false
  data_cfg:
    # Tokenizer and featurizer for pretokenizing inputs
    tokenizer:
      _target_: allatom_design.data.tokenize.boltz.BoltzTokenizer

    # Featurizer for prefeaturizing inputs
    featurizer:
      _target_: allatom_design.data.feature.seq_des_featurizer.SequenceDesignFeaturizer

    atoms_per_window_queries: 32
    num_bins: 64

esmfold:
  max_tokens_per_batch: 1024


af2_interface:
  data_dir: null
  num_models: 1
  sample_models: true
  num_recycles: 3
  prediction_models: [0, 1]
  use_multimer: false
  hard_target: false
  rm_target_seq: true
  rm_target_sc: true
  rm_template_ic: false
