log_af3_training_losses_callback:
    _target_: modelhub.callbacks.train_logging.LogAF3TrainingLossesCallback
    log_every_n: 10
    log_full_batch_losses: true

log_learning_rate_callback:
    _target_: modelhub.callbacks.train_logging.LogLearningRateCallback
    log_every_n: 10

log_model_parameters_callback:
    _target_: modelhub.callbacks.train_logging.LogModelParametersCallback

log_dataset_sampling_ratios_callback:
    _target_: modelhub.callbacks.train_logging.LogDatasetSamplingRatiosCallback


