# Wandb configuration
wandb:
  no_wandb: false  # Disable wandb logging
  project: "allatom_design"  # Wandb project name
  wandb_id: "richardshuai"  # Wandb username
  group: "debug" # Wandb group name

# Outputs
out_dir: "out_dir/train_atom_denoiser"  # Output path for trained models
exp_name: null  # Wandb exp name

# Run settings
cuda: True
num_workers: 8  # Dataloader num workers

train:
  seed: 0
  batch_size: 128  # multiplied by number of GPUs
  compile_model: false  # Compile the model before running, speeds up training a lot

# Some trainer options
trainer:
  strategy: ddp  # use "ddp_find_unused_parameters_true" if expecting unused parameters in model
  max_epochs: 100000
  accumulate_grad_batches: 1
  detect_anomaly: false  # Slower; enable for debugging nans in gradients
  gradient_clip_val: 0.0
  precision: "bf16-mixed"  # bf16-mixed  TODO: compare against fp32 as baseline
  check_val_every_n_epoch: 5  # How often to run validation

# Resuming training options
resume:
  ckpt_path: null  # Path to checkpoint to resume from, null to disable
  use_current_cfg: false  # whether to override the config in the checkpoint with the current config
  overrides: {}  # add any specific overrides to apply to the config

data:
  task: ${task}
  pdb_path: /media/scratch/datasets/augmented_af3_monomer_v2_boltz
  tokenizer:
    _target_: allatom_design.data.tokenize.boltz.BoltzTokenizer
  featurizer:
    _target_: allatom_design.data.feature.ad_featurizer.ADFeaturizer

  augmented_filters:
    # filters for augmented datasets
    - _target_: allatom_design.data.filter.dynamic.size.SizeFilter
      min_chains: 1
      max_chains: 1
    - _target_: allatom_design.data.filter.dynamic.max_residues.MaxResiduesFilter
      min_residues: 32
      max_residues: 256
    - _target_: allatom_design.data.filter.dynamic.rel_rog.RelRogFilter
      max_rel_rog: 1.4
    - _target_: allatom_design.data.filter.dynamic.self_consistency.SelfConsistencyFilter
      max_scrmsd: 2.0

  boltz_filters:
    # filters for experimental datasets
    - _target_: allatom_design.data.filter.dynamic.size.SizeFilter
      min_chains: 1
      max_chains: 50
    - _target_: allatom_design.data.filter.dynamic.date.DateFilter
      date: "2021-09-30"
      ref: released
    - _target_: allatom_design.data.filter.dynamic.resolution.ResolutionFilter
      resolution: 5.0
    - _target_: allatom_design.data.filter.dynamic.max_residues.MaxResiduesFilter
      min_residues: 16
      max_residues: 4096
    - _target_: allatom_design.data.filter.dynamic.chain_type_size.ChainTypeSizeFilter
      chain_type: "PROTEIN"
      min_chains: 1
      max_chains: null
      min_residues: 32
      max_residues: 2048

  boltz_val_filters:
    - ${data.boltz_filters.0}
    - ${data.boltz_filters.3}
    - ${data.boltz_filters.4}


  sampler:
    _target_: allatom_design.data.sample.cluster.ClusterSampler
  cropper:
    _target_: allatom_design.data.crop.identity.IdentityCropper

  # Dataset options
  overfit: -1 # Number of examples to overfit to, -1 to disable
  samples_per_epoch: 128000
  batch_size: ${train.batch_size}
  num_workers: ${num_workers}
  random_seed: ${train.seed}
  se3_augment_cfg:
    enabled: true
    translation_scale: 1.0

  # Backbone diffusion featurization options
  max_tokens: 256
  max_atoms: null  # currently unused

  # Whether to use auth_seq_id as the residue_index during featurization. Should be true for augmented dataset (backwards compatibility since we didn't keep SEQRES records), but false for boltz_v2. TODO: remove this option after we have a new augmented dataset
  use_auth_as_residx: false

  # Motif featurization options
  motif_feats:
    motif_max_tokens: 32
    motif_max_atoms: 288
    motif_atoms_per_window_queries: 32
    motif_num_bins: 64

  motif_cropper:
    _target_: allatom_design.data.crop.random_uid.RandomUIDCropper

  motif_featurizer:
    _target_: allatom_design.data.feature.motif_featurizer.MotifFeaturizer

  motif_selector:
    _target_: allatom_design.data.motif_selector.MotifSelector
    cfg: ${motif_selector}

# Model options
defaults:
  - _self_
  - denoiser: dit_denoiser
  - motif_selector: motif_selector

task: "backbone"  # "backbone", "scaffold"
model:
  task: ${task}
  sigma_data: 10  # backbone sigma data
  eps: 1.0e-8
  inf: 1.0e9
  n_aatype: 21
  denoiser: ${denoiser}
  ema:
    use_phema: false  # use post-hoc EMA
    ema_decay: 0.99  # if not using phema, use this decay rate

eval:
  eval_timesteps_bb: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]  # backbone timesteps to evaluate at

loss:
  task: ${model.task}
  loss_weights:
    bb:
      # loss on all backbone tokens
      mse_loss: 1.0
    motif:
      # loss on motif tokens
      mse_loss: 0.0
    motif_proximity_bb:
      # loss on backbone tokens with weights 1 / (1 + d^p) where d is the distance to closest motif coordinates
      mse_loss: 0.0

  motif_proximity_bb:
    p: 2.0  # power of distance in proximity kernel


optim:
  optimizer: "adam_inv_sqrt"
  adamw:
    lr: 1.0e-4
    warmup_steps: 1000
  noam:
    factor: 2
    warmup_steps: 4000
  adam_inv_sqrt:
    ref_lr: 1.0e-3
    ref_steps: 30000
    warmup_steps: 10000

logging:
  log_dir: ${out_dir}
  log_every_n_steps: 500
  wandb_watch_freq: 5000  # Log gradients every n steps

checkpointing:
  save_latest_every_n_steps: 25000  # Save the model every n steps
  save_for_resuming_every_n_epochs: 25  # Keep 1 latest copy of the model every n epochs, for resuming
  save_phema_every_n_steps: 20000  # If using post-hoc EMA, save snapshot every n steps

hydra:
  run:
    dir: /data/research/hydra_outputs # /media/scratch/huang_lab/allatom_design/hydra_outputs
