# Wandb configuration
project: "allatom_design"  # Wandb project name
wandb_id: "richardshuai"  # Wandb username
exp_name: null # Wandb exp name
group: "debug" # Wandb group name

# Run settings
no_wandb: false # Disable wandb logging
overfit: -1 # Number of examples to overfit to, -1 to disable
cuda: True
num_workers: 10 # Dataloader num workers
out_dir: "out_dir/train_atom_denoiser"  # Output path for trained models

train:
  seed: 0
  batch_size: 8
  compile_model: false  # Compile the model before running, speeds up training a lot

# Some trainer options
trainer:
  strategy: ddp  # use "ddp_find_unused_parameters_true" if expecting unused parameters in model
  max_epochs: 100000
  accumulate_grad_batches: 1
  detect_anomaly: false  # Slower; enable for debugging nans in gradients
  gradient_clip_val: 0.0
  precision: "bf16-mixed"  # bf16-mixed  TODO: compare against fp32 as baseline
  check_val_every_n_epoch: 50  # How often to run validation

# Resuming training options
resume:
  ckpt_path: null  # Path to checkpoint to resume from, null to disable
  # use_current_cfg: false  # whether to override the config in the checkpoint with the current config
  # overrides: {}  # add any specific overrides to apply to the config

# Data options
data:
    # first dataset is the "primary" dataset
    pdb_paths: [/media/scratch/datasets/ingraham_cath_dataset, /media/scratch/datasets/afdb]
    # pdb_paths: [/media/scratch/datasets/ingraham_cath_dataset]
    designability_csvs: [/media/scratch/datasets/ingraham_cath_dataset/all_esmfold_native_with_cath_gapped_with_tm_with_seq.csv, null]
    # designability_csvs: [/media/scratch/datasets/ingraham_cath_dataset/all_esmfold_native_with_cath_gapped_with_tm_with_seq.csv]
    dataset_weights: [0.25, 0.75]  # probability of selecting each dataset
    # dataset_weights: [1.0]  # probability of selecting each dataset
    fixed_size: 128
    overfit: ${overfit}
    short_epoch: false
    n_random_subset: null
    se3_augment: true  # randomly rotate and translate data
    translation_scale: 0.0  # scale of the translation augmentation
    overwrite_cache: false  # overwrite the cached dataset

# Model options
defaults:
  - _self_
  - denoiser: dit_denoiser
  - sd_interpolant: mar_interpolant

model:
  task: "backbone"  # "backbone"
  scale_factor_mode: null  # filled in based on the denoiser and its interpolant
  eps: 1.0e-8
  inf: 1.0e9
  denoiser: ${denoiser}
  sd_interpolant: ${sd_interpolant}

eval:
  eval_timesteps_bb: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]  # backbone timesteps to evaluate at
  eval_timesteps_seq: []  # seq timesteps to evaluate at


loss:
  task: ${model.task}
  loss_weights:
    bb:
      mse_loss: 1.0

optim:
  optimizer: "adamw"
  adamw:
    lr: 1.0e-4
    warmup_steps: 1000
  noam:
    factor: 2
    warmup_steps: 4000
  adam_inv_sqrt:
    ref_lr: 1.0e-2
    ref_steps: 70000
    warmup_steps: 1000

logging:
  log_dir: ${out_dir}
  log_every_n_steps: 500
  wandb_watch_freq: 5000  # Log gradients every n steps

checkpointing:
  save_latest_every_n_steps: 50000  # Save the full model every n steps
  save_ema_every_n_steps: 20000  # Save the EMA model every n steps
  save_top_k: 1

hydra:
  run:
    dir: /media/scratch/huang_lab/allatom_design/hydra_outputs
