# @package _global_

defaults:
  - base
  - _self_

_target_: modelhub.inference_engines.rf3.RF3InferenceEngine

ckpt_path: rf3_latest.pt

# Transform arguments
n_recycles: 10
diffusion_batch_size: 5

# Sampling
num_steps: 50
solver: "af3"

# Inference arguments
early_stopping_plddt_threshold: 0.5
residue_renaming_dict: null
template_selection: null
ground_truth_conformer_selection: null
seed: null
skip_existing: false
print_config: true
raise_if_missing_msa_for_protein_of_length_n: null

# I/O
dump_predictions: true
dump_trajectories: false
one_model_per_file: false
annotate_b_factor_with_plddt: true

# Metrics
metrics_cfg:
  # (For confidence outputs)
  ptm:
    _target_: modelhub.metrics.predicted_error.ComputePTM
  iptm:
    _target_: modelhub.metrics.predicted_error.ComputeIPTM
  count_clashing_chains:
    _target_: modelhub.metrics.clashing_chains.CountClashingChains