name: scaffold_manager

contiguous_p: 0.25
discontiguous_p: 0.5
max_span_len: 20
max_discontiguous_res: 20
dist_threshold: 12.0

translation_scale: ${data.translation_scale}
se3_augment: ${data.se3_augment}

